import 'package:flutter/material.dart';
import 'package:shadcn_ui/shadcn_ui.dart';

/// "Branding Overlays: automatically apply a subtle 'Generated by
/// GrowthPilotAI' watermark and a timestamp" (Issue #248) — baked into
/// the widget tree so it's part of the captured raster, not a
/// post-processing overlay.
class DashboardBrandingFooter extends StatelessWidget {
  const DashboardBrandingFooter({super.key});

  @override
  Widget build(BuildContext context) {
    final colors = ShadTheme.of(context).colorScheme;
    return Padding(
      padding: const EdgeInsets.only(top: 16),
      child: Text('Generated by GrowthPilotAI · ${DateTime.now().toIso8601String()}',
          style: TextStyle(color: colors.mutedForeground, fontSize: 9)),
    );
  }
}
