name: growth_pilot_ai
description: "A high-performance B2B ecosystem and cloud management mobile application."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  intl: ^0.20.2
  image: ^4.3.0

  # --- Core & Security ---
  get: ^4.6.6
  flutter_secure_storage: ^9.0.0
  image_picker: ^1.1.2
  image_cropper: ^8.0.2

  # --- Security & Hashing ---
  crypto: ^3.0.7
  encrypt: ^5.0.3

  # --- UI, Fonts & Themes ---
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  adaptive_theme: ^3.7.0
  fl_chart: ^0.66.0
  flutter_animate: ^4.5.0
  graphview: ^1.2.0

  # --- Database & Persistence ---
  objectbox: ^2.5.1
  objectbox_flutter_libs: any
  path_provider: ^2.1.2
  path: ^1.9.0

  # --- Networking & Connectivity ---
  connectivity_plus: ^6.0.3

  # --- AI & Machine Learning ---
  google_mlkit_text_recognition: ^0.15.1
  permission_handler: ^12.0.1
  flutter_bounceable: ^1.2.0
  flutter_tesseract_ocr: ^0.4.30
  logger: ^2.7.0
  tflite_flutter: ^0.12.1
  get_it: ^9.2.1
  shadcn_ui: ^0.55.0
  flutter_staggered_grid_view: ^0.7.0

  # --- Export & Sharing ---
  pdf: ^3.12.0
  printing: ^5.14.3
  share_plus: ^12.0.2
  url_launcher: ^6.3.1

  # --- Performance ---
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9
  objectbox_generator: ^2.5.1
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/models/mobilenet_v2_1.0_224_quant.tflite
