// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types, depend_on_referenced_packages
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'
    as obx_int; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart' as obx;
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'core/data/entities/category_entity.dart';
import 'core/data/entities/placeholder.dart';
import 'core/data/entities/transaction_entity.dart';
import 'core/data/entities/vendor_entity.dart';
import 'core/models/document_type.dart';
import 'core/models/error_log.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <obx_int.ModelEntity>[
  obx_int.ModelEntity(
      id: const obx_int.IdUid(1, 67337174511996417),
      name: 'Placeholder',
      lastPropertyId: const obx_int.IdUid(2, 6246572223294898780),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 1258891592734998716),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6246572223294898780),
            name: 'name',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(2, 1174740264999713832),
      name: 'TransactionEntity',
      lastPropertyId: const obx_int.IdUid(12, 3154185988222372620),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3789422012756364590),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6189674884955974714),
            name: 'remoteId',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(1, 7830325081359151234)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 7113379022415804864),
            name: 'amount',
            type: 8,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2738589454532399497),
            name: 'date',
            type: 10,
            flags: 8,
            indexId: const obx_int.IdUid(2, 4915629178925196983)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 654865347946668006),
            name: 'description',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 861393444512325952),
            name: 'dbType',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(7, 2385658356732858890),
            name: 'dbSyncStatus',
            type: 6,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(8, 719912908538945673),
            name: 'categoryId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(4, 3249461905516396650),
            relationTarget: 'CategoryEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(9, 6400372292870148815),
            name: 'vendorId',
            type: 11,
            flags: 520,
            indexId: const obx_int.IdUid(5, 1510582073196436695),
            relationTarget: 'VendorEntity'),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(10, 6135345771449429271),
            name: 'memo',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(11, 2590928845301501178),
            name: 'lastModified',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(12, 3154185988222372620),
            name: 'isDeleted',
            type: 1,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(3, 8819637758054597445),
      name: 'CategoryEntity',
      lastPropertyId: const obx_int.IdUid(4, 1657266967055710644),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2148477426849493168),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 5972478490283912979),
            name: 'name',
            type: 9,
            flags: 2080,
            indexId: const obx_int.IdUid(3, 4779792483439617371)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3300967026362909282),
            name: 'icon',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 1657266967055710644),
            name: 'color',
            type: 6,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'transactions',
            srcEntity: 'TransactionEntity',
            srcField: 'category')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(4, 423798553179985044),
      name: 'VendorEntity',
      lastPropertyId: const obx_int.IdUid(3, 6242450742222365948),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 7199356901433504403),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 6017401882564850810),
            name: 'name',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(6, 8228385944914176999)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 6242450742222365948),
            name: 'taxId',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[
        obx_int.ModelBacklink(
            name: 'transactions',
            srcEntity: 'TransactionEntity',
            srcField: 'vendor')
      ]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(6, 8897868831705587762),
      name: 'DocumentTypeEntity',
      lastPropertyId: const obx_int.IdUid(4, 5385969681087342381),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 2797120440896798576),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 4643943187783766031),
            name: 'name',
            type: 9,
            flags: 2048,
            indexId: const obx_int.IdUid(8, 3170650326812969352)),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3654922943520830378),
            name: 'isPublic',
            type: 1,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 5385969681087342381),
            name: 'iconName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[]),
  obx_int.ModelEntity(
      id: const obx_int.IdUid(7, 5361462158824125226),
      name: 'ErrorLog',
      lastPropertyId: const obx_int.IdUid(6, 8083298058714824134),
      flags: 0,
      properties: <obx_int.ModelProperty>[
        obx_int.ModelProperty(
            id: const obx_int.IdUid(1, 3009188414961791544),
            name: 'id',
            type: 6,
            flags: 1),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(2, 1568636352268206772),
            name: 'title',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(3, 3744718890590156870),
            name: 'message',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(4, 2270540707766054018),
            name: 'stackTrace',
            type: 9,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(5, 3089991431830755700),
            name: 'timestamp',
            type: 10,
            flags: 0),
        obx_int.ModelProperty(
            id: const obx_int.IdUid(6, 8083298058714824134),
            name: 'widgetName',
            type: 9,
            flags: 0)
      ],
      relations: <obx_int.ModelRelation>[],
      backlinks: <obx_int.ModelBacklink>[])
];

/// Shortcut for [Store.new] that passes [getObjectBoxModel] and for Flutter
/// apps by default a [directory] using `defaultStoreDirectory()` from the
/// ObjectBox Flutter library.
///
/// Note: for desktop apps it is recommended to specify a unique [directory].
///
/// See [Store.new] for an explanation of all parameters.
///
/// For Flutter apps, also calls `loadObjectBoxLibraryAndroidCompat()` from
/// the ObjectBox Flutter library to fix loading the native ObjectBox library
/// on Android 6 and older.
Future<obx.Store> openStore(
    {String? directory,
    int? maxDBSizeInKB,
    int? maxDataSizeInKB,
    int? fileMode,
    int? maxReaders,
    bool queriesCaseSensitiveDefault = true,
    String? macosApplicationGroup}) async {
  await loadObjectBoxLibraryAndroidCompat();
  return obx.Store(getObjectBoxModel(),
      directory: directory ?? (await defaultStoreDirectory()).path,
      maxDBSizeInKB: maxDBSizeInKB,
      maxDataSizeInKB: maxDataSizeInKB,
      fileMode: fileMode,
      maxReaders: maxReaders,
      queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
      macosApplicationGroup: macosApplicationGroup);
}

/// Returns the ObjectBox model definition for this project for use with
/// [Store.new].
obx_int.ModelDefinition getObjectBoxModel() {
  final model = obx_int.ModelInfo(
      entities: _entities,
      lastEntityId: const obx_int.IdUid(7, 5361462158824125226),
      lastIndexId: const obx_int.IdUid(8, 3170650326812969352),
      lastRelationId: const obx_int.IdUid(0, 0),
      lastSequenceId: const obx_int.IdUid(0, 0),
      retiredEntityUids: const [1407349826204092014],
      retiredIndexUids: const [],
      retiredPropertyUids: const [
        3822539053991719425,
        4314188896221551808,
        1570878085546655654,
        3274884444133419373
      ],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, obx_int.EntityDefinition>{
    Placeholder: obx_int.EntityDefinition<Placeholder>(
        model: _entities[0],
        toOneRelations: (Placeholder object) => [],
        toManyRelations: (Placeholder object) => {},
        getId: (Placeholder object) => object.id,
        setId: (Placeholder object, int id) {
          object.id = id;
        },
        objectToFB: (Placeholder object, fb.Builder fbb) {
          final nameOffset =
              object.name == null ? null : fbb.writeString(object.name!);
          fbb.startTable(3);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 6);
          final object = Placeholder(id: idParam, name: nameParam);

          return object;
        }),
    TransactionEntity: obx_int.EntityDefinition<TransactionEntity>(
        model: _entities[1],
        toOneRelations: (TransactionEntity object) =>
            [object.category, object.vendor],
        toManyRelations: (TransactionEntity object) => {},
        getId: (TransactionEntity object) => object.id,
        setId: (TransactionEntity object, int id) {
          object.id = id;
        },
        objectToFB: (TransactionEntity object, fb.Builder fbb) {
          final remoteIdOffset = object.remoteId == null
              ? null
              : fbb.writeString(object.remoteId!);
          final descriptionOffset = fbb.writeString(object.description);
          final memoOffset =
              object.memo == null ? null : fbb.writeString(object.memo!);
          fbb.startTable(13);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, remoteIdOffset);
          fbb.addFloat64(2, object.amount);
          fbb.addInt64(3, object.date.millisecondsSinceEpoch);
          fbb.addOffset(4, descriptionOffset);
          fbb.addInt64(5, object.dbType);
          fbb.addInt64(6, object.dbSyncStatus);
          fbb.addInt64(7, object.category.targetId);
          fbb.addInt64(8, object.vendor.targetId);
          fbb.addOffset(9, memoOffset);
          fbb.addInt64(10, object.lastModified.millisecondsSinceEpoch);
          fbb.addBool(11, object.isDeleted);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final amountParam =
              const fb.Float64Reader().vTableGet(buffer, rootOffset, 8, 0);
          final dateParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0));
          final descriptionParam =
              const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 12, '');
          final dbTypeParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0);
          final dbSyncStatusParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 16, 0);
          final isDeletedParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 26, false);
          final lastModifiedParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 24, 0));
          final object = TransactionEntity(
              id: idParam,
              amount: amountParam,
              date: dateParam,
              description: descriptionParam,
              dbType: dbTypeParam,
              dbSyncStatus: dbSyncStatusParam,
              isDeleted: isDeletedParam,
              lastModified: lastModifiedParam)
            ..remoteId = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 6)
            ..memo = const fb.StringReader(asciiOptimization: true)
                .vTableGetNullable(buffer, rootOffset, 22);
          object.category.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 18, 0);
          object.category.attach(store);
          object.vendor.targetId =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 20, 0);
          object.vendor.attach(store);
          return object;
        }),
    CategoryEntity: obx_int.EntityDefinition<CategoryEntity>(
        model: _entities[2],
        toOneRelations: (CategoryEntity object) => [],
        toManyRelations: (CategoryEntity object) => {
              obx_int.RelInfo<TransactionEntity>.toOneBacklink(8, object.id,
                      (TransactionEntity srcObject) => srcObject.category):
                  object.transactions
            },
        getId: (CategoryEntity object) => object.id,
        setId: (CategoryEntity object, int id) {
          object.id = id;
        },
        objectToFB: (CategoryEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final iconOffset = fbb.writeString(object.icon);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, iconOffset);
          fbb.addInt64(3, object.color);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final iconParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final colorParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0);
          final object = CategoryEntity(
              id: idParam, name: nameParam, icon: iconParam, color: colorParam);
          obx_int.InternalToManyAccess.setRelInfo<CategoryEntity>(
              object.transactions,
              store,
              obx_int.RelInfo<TransactionEntity>.toOneBacklink(8, object.id,
                  (TransactionEntity srcObject) => srcObject.category));
          return object;
        }),
    VendorEntity: obx_int.EntityDefinition<VendorEntity>(
        model: _entities[3],
        toOneRelations: (VendorEntity object) => [],
        toManyRelations: (VendorEntity object) => {
              obx_int.RelInfo<TransactionEntity>.toOneBacklink(9, object.id,
                      (TransactionEntity srcObject) => srcObject.vendor):
                  object.transactions
            },
        getId: (VendorEntity object) => object.id,
        setId: (VendorEntity object, int id) {
          object.id = id;
        },
        objectToFB: (VendorEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final taxIdOffset =
              object.taxId == null ? null : fbb.writeString(object.taxId!);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addOffset(2, taxIdOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final idParam =
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final taxIdParam = const fb.StringReader(asciiOptimization: true)
              .vTableGetNullable(buffer, rootOffset, 8);
          final object =
              VendorEntity(id: idParam, name: nameParam, taxId: taxIdParam);
          obx_int.InternalToManyAccess.setRelInfo<VendorEntity>(
              object.transactions,
              store,
              obx_int.RelInfo<TransactionEntity>.toOneBacklink(9, object.id,
                  (TransactionEntity srcObject) => srcObject.vendor));
          return object;
        }),
    DocumentTypeEntity: obx_int.EntityDefinition<DocumentTypeEntity>(
        model: _entities[4],
        toOneRelations: (DocumentTypeEntity object) => [],
        toManyRelations: (DocumentTypeEntity object) => {},
        getId: (DocumentTypeEntity object) => object.id,
        setId: (DocumentTypeEntity object, int id) {
          object.id = id;
        },
        objectToFB: (DocumentTypeEntity object, fb.Builder fbb) {
          final nameOffset = fbb.writeString(object.name);
          final iconNameOffset = fbb.writeString(object.iconName);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, nameOffset);
          fbb.addBool(2, object.isPublic);
          fbb.addOffset(3, iconNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final nameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final isPublicParam =
              const fb.BoolReader().vTableGet(buffer, rootOffset, 8, false);
          final iconNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final object = DocumentTypeEntity(
              name: nameParam, isPublic: isPublicParam, iconName: iconNameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        }),
    ErrorLog: obx_int.EntityDefinition<ErrorLog>(
        model: _entities[5],
        toOneRelations: (ErrorLog object) => [],
        toManyRelations: (ErrorLog object) => {},
        getId: (ErrorLog object) => object.id,
        setId: (ErrorLog object, int id) {
          object.id = id;
        },
        objectToFB: (ErrorLog object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final messageOffset = fbb.writeString(object.message);
          final stackTraceOffset = fbb.writeString(object.stackTrace);
          final widgetNameOffset = fbb.writeString(object.widgetName);
          fbb.startTable(7);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, messageOffset);
          fbb.addOffset(3, stackTraceOffset);
          fbb.addInt64(4, object.timestamp.millisecondsSinceEpoch);
          fbb.addOffset(5, widgetNameOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (obx.Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);
          final titleParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 6, '');
          final messageParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 8, '');
          final stackTraceParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 10, '');
          final timestampParam = DateTime.fromMillisecondsSinceEpoch(
              const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0));
          final widgetNameParam = const fb.StringReader(asciiOptimization: true)
              .vTableGet(buffer, rootOffset, 14, '');
          final object = ErrorLog(
              title: titleParam,
              message: messageParam,
              stackTrace: stackTraceParam,
              timestamp: timestampParam,
              widgetName: widgetNameParam)
            ..id = const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0);

          return object;
        })
  };

  return obx_int.ModelDefinition(model, bindings);
}

/// [Placeholder] entity fields to define ObjectBox queries.
class Placeholder_ {
  /// see [Placeholder.id]
  static final id =
      obx.QueryIntegerProperty<Placeholder>(_entities[0].properties[0]);

  /// see [Placeholder.name]
  static final name =
      obx.QueryStringProperty<Placeholder>(_entities[0].properties[1]);
}

/// [TransactionEntity] entity fields to define ObjectBox queries.
class TransactionEntity_ {
  /// see [TransactionEntity.id]
  static final id =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[1].properties[0]);

  /// see [TransactionEntity.remoteId]
  static final remoteId =
      obx.QueryStringProperty<TransactionEntity>(_entities[1].properties[1]);

  /// see [TransactionEntity.amount]
  static final amount =
      obx.QueryDoubleProperty<TransactionEntity>(_entities[1].properties[2]);

  /// see [TransactionEntity.date]
  static final date =
      obx.QueryDateProperty<TransactionEntity>(_entities[1].properties[3]);

  /// see [TransactionEntity.description]
  static final description =
      obx.QueryStringProperty<TransactionEntity>(_entities[1].properties[4]);

  /// see [TransactionEntity.dbType]
  static final dbType =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[1].properties[5]);

  /// see [TransactionEntity.dbSyncStatus]
  static final dbSyncStatus =
      obx.QueryIntegerProperty<TransactionEntity>(_entities[1].properties[6]);

  /// see [TransactionEntity.category]
  static final category =
      obx.QueryRelationToOne<TransactionEntity, CategoryEntity>(
          _entities[1].properties[7]);

  /// see [TransactionEntity.vendor]
  static final vendor = obx.QueryRelationToOne<TransactionEntity, VendorEntity>(
      _entities[1].properties[8]);

  /// see [TransactionEntity.memo]
  static final memo =
      obx.QueryStringProperty<TransactionEntity>(_entities[1].properties[9]);

  /// see [TransactionEntity.lastModified]
  static final lastModified =
      obx.QueryDateProperty<TransactionEntity>(_entities[1].properties[10]);

  /// see [TransactionEntity.isDeleted]
  static final isDeleted =
      obx.QueryBooleanProperty<TransactionEntity>(_entities[1].properties[11]);
}

/// [CategoryEntity] entity fields to define ObjectBox queries.
class CategoryEntity_ {
  /// see [CategoryEntity.id]
  static final id =
      obx.QueryIntegerProperty<CategoryEntity>(_entities[2].properties[0]);

  /// see [CategoryEntity.name]
  static final name =
      obx.QueryStringProperty<CategoryEntity>(_entities[2].properties[1]);

  /// see [CategoryEntity.icon]
  static final icon =
      obx.QueryStringProperty<CategoryEntity>(_entities[2].properties[2]);

  /// see [CategoryEntity.color]
  static final color =
      obx.QueryIntegerProperty<CategoryEntity>(_entities[2].properties[3]);

  /// see [CategoryEntity.transactions]
  static final transactions =
      obx.QueryBacklinkToMany<TransactionEntity, CategoryEntity>(
          TransactionEntity_.category);
}

/// [VendorEntity] entity fields to define ObjectBox queries.
class VendorEntity_ {
  /// see [VendorEntity.id]
  static final id =
      obx.QueryIntegerProperty<VendorEntity>(_entities[3].properties[0]);

  /// see [VendorEntity.name]
  static final name =
      obx.QueryStringProperty<VendorEntity>(_entities[3].properties[1]);

  /// see [VendorEntity.taxId]
  static final taxId =
      obx.QueryStringProperty<VendorEntity>(_entities[3].properties[2]);

  /// see [VendorEntity.transactions]
  static final transactions =
      obx.QueryBacklinkToMany<TransactionEntity, VendorEntity>(
          TransactionEntity_.vendor);
}

/// [DocumentTypeEntity] entity fields to define ObjectBox queries.
class DocumentTypeEntity_ {
  /// see [DocumentTypeEntity.id]
  static final id =
      obx.QueryIntegerProperty<DocumentTypeEntity>(_entities[4].properties[0]);

  /// see [DocumentTypeEntity.name]
  static final name =
      obx.QueryStringProperty<DocumentTypeEntity>(_entities[4].properties[1]);

  /// see [DocumentTypeEntity.isPublic]
  static final isPublic =
      obx.QueryBooleanProperty<DocumentTypeEntity>(_entities[4].properties[2]);

  /// see [DocumentTypeEntity.iconName]
  static final iconName =
      obx.QueryStringProperty<DocumentTypeEntity>(_entities[4].properties[3]);
}

/// [ErrorLog] entity fields to define ObjectBox queries.
class ErrorLog_ {
  /// see [ErrorLog.id]
  static final id =
      obx.QueryIntegerProperty<ErrorLog>(_entities[5].properties[0]);

  /// see [ErrorLog.title]
  static final title =
      obx.QueryStringProperty<ErrorLog>(_entities[5].properties[1]);

  /// see [ErrorLog.message]
  static final message =
      obx.QueryStringProperty<ErrorLog>(_entities[5].properties[2]);

  /// see [ErrorLog.stackTrace]
  static final stackTrace =
      obx.QueryStringProperty<ErrorLog>(_entities[5].properties[3]);

  /// see [ErrorLog.timestamp]
  static final timestamp =
      obx.QueryDateProperty<ErrorLog>(_entities[5].properties[4]);

  /// see [ErrorLog.widgetName]
  static final widgetName =
      obx.QueryStringProperty<ErrorLog>(_entities[5].properties[5]);
}
