// Mocks generated by Mockito 5.4.4 from annotations
// in growth_pilot_ai/test/features/analytics/document_classification/business/controllers/ocr_confirmation_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:growth_pilot_ai/core/data/entities/transaction_entity.dart'
    as _i4;
import 'package:growth_pilot_ai/core/data/repositories/transaction_repository.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

/// A class which mocks [TransactionRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockTransactionRepository extends _i1.Mock
    implements _i2.TransactionRepository {
  MockTransactionRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<List<_i4.TransactionEntity>> watchAll() => (super.noSuchMethod(
        Invocation.method(
          #watchAll,
          [],
        ),
        returnValue: _i3.Stream<List<_i4.TransactionEntity>>.empty(),
      ) as _i3.Stream<List<_i4.TransactionEntity>>);

  @override
  List<_i4.TransactionEntity> getByDateRange(
    DateTime? start,
    DateTime? end,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #getByDateRange,
          [
            start,
            end,
          ],
        ),
        returnValue: <_i4.TransactionEntity>[],
      ) as List<_i4.TransactionEntity>);

  @override
  List<_i4.TransactionEntity> search(String? text) => (super.noSuchMethod(
        Invocation.method(
          #search,
          [text],
        ),
        returnValue: <_i4.TransactionEntity>[],
      ) as List<_i4.TransactionEntity>);

  @override
  List<_i4.TransactionEntity> getAdvancedFilter({
    int? categoryId,
    _i4.TransactionType? type,
    bool? sortByLargest = false,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #getAdvancedFilter,
          [],
          {
            #categoryId: categoryId,
            #type: type,
            #sortByLargest: sortByLargest,
          },
        ),
        returnValue: <_i4.TransactionEntity>[],
      ) as List<_i4.TransactionEntity>);

  @override
  void compactDatabase() => super.noSuchMethod(
        Invocation.method(
          #compactDatabase,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
